.TH elfexec 1 "Jan 4, 2019"
.nh
.ad left
.SH NAME
elfexec \- utility to execute ELF binary directly from stdin pipe. It is useful to run binary via SSH without copy or install it on remote systems.
.SH SYNTAX
.B elfexec
.RI [ options ]
.SH OPTIONS
Executed binary options.
.SH EXIT CODE
Executed binary exit code or 1 if self failed.
.SH EXAMPLE
.TP
$ cat build-1234 | ssh user@host 'elfexec --test=integration --env=production'
